export const dataProducts = [
  {
    id: 1,
    name: "Pizza",
    amount: 1,
    price: 370,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,address2,address2",
    img: "./images/Food/Pizza.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Restaurant.jpg",
    restaurantName: "Easy Foods",
  },
  {
    id: 2,
    name: "Rice",
    amount: 1,
    price: 250.5,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,address2,address2,address2",
    img: "./images/Rice1.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (5).jpg",
    restaurantName: "Kam Kum",
  },
  {
    id: 3,
    name: "Cake",
    amount: 1,
    price: 200.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,address2,address2,address2",
    img: "./images/Food/cake.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (2).jpg",
    restaurantName: "Kam Kum",
  },
  {
    id: 4,
    name: "Noodles",
    amount: 1,
    price: 150.75,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,address2,address2,address2",
    img: "./images/Food/Nuudle2.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (3).jpg",
    restaurantName: "Bon Bon",
  },
  {
    id: 5,
    name: "Coffie",
    amount: 1,
    price: 80.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,address2,address2,address2",
    img: "./images/Food/Coffie.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (6).jpg",
    restaurantName: "Kam Kum",
  },
  {
    id: 6,
    name: "Noodles",
    amount: 1,
    price: 150.75,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,address2,address2,address2",
    img: "./images/Food/Nuudle2.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (2).jpg",
    restaurantName: "Bon Bon",
  },

  {
    id: 7,
    name: "Rice",
    amount: 1,
    price: 350.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/Food1.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (7).jpg",
    restaurantName: "Kuruppu Stores",
  },
  {
    id: 8,
    name: "Cream Cracker",
    amount: 1,
    price: 100.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "grocery",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/grocery/Cream-cracker.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (2).jpg",
    restaurantName: "Saman Stores",
  },
  {
    id: 9,
    name: "Product",
    amount: 1,
    price: 80.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "grocery",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/grocery/oreo.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (3).jpg",
    restaurantName: "Kuruppu Stores",
  },
  {
    id: 10,
    name: "Peanut-butter",
    amount: 1,
    price: 450.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "grocery",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/grocery/Peanut-butter.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (4).jpg",
    restaurantName: "Saman Stores",
  },
  {
    id: 11,
    name: "cocacola",
    amount: 1,
    price: 120.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "grocery",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/grocery/cocacola.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (8).jpg",
    restaurantName: "Saman Stores",
  },
  {
    id: 12,
    name: "Eggs",
    amount: 1,
    price: 25.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "grocery",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/grocery/egg.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (8).jpg",
    restaurantName: "Saman Stores",
  },
  {
    id: 13,
    name: "Saman",
    amount: 1,
    price: 150.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "grocery",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/grocery/Saman.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (7).jpg",
    restaurantName: "KK Stores",
  },

  {
    id: 14,
    name: "Mask",
    amount: 1,
    price: 100.0,
    inCart: false,
    total: 0,
    count: 0,
    category: "healthcare",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/Healthcare/masks.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (6).jpg",
    restaurantName: "Sanduni Farmacy",
  },
  {
    id: 15,
    name: "Sanitizer",
    amount: 1,
    price: 140.55,
    inCart: false,
    total: 0,
    count: 0,
    category: "healthcare",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/Healthcare/sanitizer.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (5).jpg",
    restaurantName: "Renuka Farmacy",
  },
  {
    id: 16,
    name: "Dettol",
    amount: 1,
    price: 200.5,
    inCart: false,
    total: 0,
    count: 0,
    category: "healthcare",
    location: "matara",
    address: "Address,addressl,address1,address1",
    img: "./images/Healthcare/Dettol.jpeg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Shop Logos/shop-logo (7).jpg",
    restaurantName: "Sanduni Farmacy",
  },
];

export const productInDetails = [
  {
    id: 1,
    name: "Pizza",
    amount: 1,
    price: 370,
    inCart: false,
    total: 0,
    count: 0,
    category: "food",
    location: "matara",
    address: "Address,address2,address2",
    img: "./images/Food/Pizza.jpg",
    thumb: {
      img1: "./images/DummeyImages/thumb1.png",
      img2: "./images/DummeyImages/thumb2.jpg",
    },
    shopImg: "./images/Restaurant.jpg",
    restaurantName: "Easy Foods",
  },
];
