export const DelivererData = [
  {
    id: 1,
    name: "Sarath Perera",
    active: false,
    type: "part-time",
    location: "matara",
    address: "Address,address2,address2",
    profileImg: "./images/DelivererProfilePic/pic1.jpg",
    avgRating: 4,
  },
  {
    id: 2,
    name: "Sadun Kumara",
    active: false,
    type: "part-time",
    location: "matara",
    address: "Address,address2,address2",
    profileImg: "./images/DelivererProfilePic/pic2.jpg",
    avgRating: 3.5,
  },
  {
    id: 3,
    name: "Harsha Ruwan",
    active: false,
    type: "part-time",
    location: "matara",
    address: "Address,address2,address2",
    profileImg: "./images/DelivererProfilePic/pic3.jpg",
    avgRating: 4.5,
  },
  {
    id: 4,
    name: "Mihira Athapaththu",
    active: false,
    type: "part-time",
    location: "matara",
    address: "Address,address2,address2",
    profileImg: "./images/DelivererProfilePic/pic4.jpg",
    avgRating: 4.5,
  },
  {
    id: 5,
    name: "Ranil Wikramage",
    active: false,
    type: "part-time",
    location: "matara",
    address: "Address,address2,address2",
    profileImg: "./images/DelivererProfilePic/pic5.jpg",
    avgRating: 4,
  },
  {
    id: 6,
    name: "Kulendra Jayathilake",
    active: false,
    type: "part-time",
    location: "matara",
    address: "Address,address2,address2",
    profileImg: "./images/DelivererProfilePic/pic6.jpg",
    avgRating: 3.5,
  },
];
